### ISSUE TITLE
wildcard permission storage.objects.* not available in GCP

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/cloud-manager-sync#20]
Page: [Creating a new data broker in Google Cloud](https://docs.netapp.com/us-en/cloud-manager-sync/task-installing-gcp.html)

Hi, 

Adding the wildcard permission storage.objects.* was not allowed when creating a custom role for the storage SA in GCP (tested in two different GCP accounts).
![image](https://user-images.githubusercontent.com/92466880/184891218-488a1e1c-4a47-4e33-a299-1835ec962bae.png)

"ERROR: (gcloud.iam.roles.create) INVALID_ARGUMENT: Permission storage.objects.* is not valid."

It worked when I listed all individual storage.objects:

storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.setIamPolicy
storage.objects.update

Thanks
Holger

**Comment by netapp-bcammett** [comment]
Hi Holger,

Thank you for letting me know. I updated the page to include the full list of storage.objects permissions.

Thanks again,
Ben
