### ISSUE TITLE
Replace Microsoft Azure with Google Cloud

### ISSUE THREAD

**Issue by melatsg** [NetAppDocs/cloud-manager-sync#22]
Page: [Creating a new data broker in Google Cloud](https://docs.netapp.com/us-en/cloud-manager-sync/task-installing-gcp.html)

Hello, in the "Creating the data broker" section there is Microsoft Azure instead of Google Cloud Platform. 

Is it possible to update the doc ?

Thanks

**Comment by netapp-bcammett** [comment]
Marco,

Thank you for catching that embarrassing copy/paste error :roll_eyes:

It's been fixed!
