### ISSUE TITLE
default client ID

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/cloud-manager-sync#39]
https://docs.netapp.com/us-en/cloud-manager-sync/api-sync.html#using-list-apis

In this page, as per below point, client ID is required to get user token.
But there is no client ID available for personal email accounts.
For all personal email accounts, we can use default client ID “QC3AgHk6qdbmC7Yyr82ApBwaaJLwRrNO” as per the document: 
https://services.cloud.netapp.com/api-doc/tenancy --> click on “learn how to authenticate”.

Please add the default client ID to be used for personal email accounts so that customer can see the document and use the same.

**Comment by netapp-ivanad** [comment]
I added a note to reference this and the page should be updated. Let me know if there's anything else to add!
