### ISSUE TITLE
Migrating from BOX, FSxN and ONTAP appear to be unsupported.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloud-manager-sync#6]
Page: [Supported sync relationships](https://docs.netapp.com/us-en/cloud-manager-sync/reference-supported-relationships.html)

It seems that migration from BOX to FSx for NetApp ONTAP is not supported.
Also, it seems that migration from BOX to On-prem ONTAP is not supported.

They should be covered with "NFS server" and "SMB server".

**Comment by netapp-bcammett** [comment]
Hi @kanitani,

After looking in Cloud Sync, I confirmed that Box to FSx and Box to on-prem ONTAP are supported. 

I updated the documentation to reflect that.

Thanks,
Ben
