### ISSUE TITLE
CloudSync data migration matrix

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/cloud-manager-sync#7]
Page: [Supported sync relationships](https://docs.netapp.com/us-en/cloud-manager-sync/reference-supported-relationships.html)
[CloudSync_matrix.pptx](https://github.com/NetAppDocs/cloud-manager-sync/files/8530558/CloudSync_matrix.pptx)

Is this matrix I attached correct?

Thanks,

**Comment by netapp-bcammett** [comment]
Hi @kanitani,

As noted in the other issue, Box should include the following as supported targets:

- Amazon S3
- Amazon FSx for ONTAP
- Azure NetApp Files
- Cloud Volumes ONTAP
- IBM Cloud Object Storage
- NFS server
- SMB Server
- StorageGRID

Regards,
Ben

**Comment by kanitani** [comment]
OK. Thanks!

Kan Itani

2022年4月22日(金) 0:22 Ben Cammett ***@***.***>:
